# Generated by Django 3.1 on 2020-08-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='enderecos',
            field=models.ManyToManyField(to='endereco.Endereco'),
        ),
    ]
