# Generated by Django 3.1 on 2020-08-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0003_remove_endereco_cliente'),
        ('cliente', '0004_remove_cliente_enderecos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='enderecos',
            field=models.ManyToManyField(to='endereco.Endereco'),
        ),
    ]
