# Generated by Django 3.1 on 2020-08-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_cliente_enderecos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.FileField(blank=True, upload_to='clientes/images'),
        ),
    ]
